#                           |------------------------------------------------------------|
#                           |        Plugin created by WHiTeG0Dz_ and for support        |
#                           | Contact me on telegram @GodzHard or Discord WHiTeG0Dz_#2791|
#                           |------------------------------------------------------------|

#The title would be the initial part of the UI
Title: JoinUI
#The description is the part below the UI
Description: Custom plugin created by GodzHard
#The first button is to close the UI
Button: Close
#The second button is to open a command of your choice (you can delete it if you don't want to)
Button2: "true"
Button2-On: Ok
#Command is to set the command of the second button
Command: info

#For my second plugin "RulesUI" click on the link! https://poggit.pmmp.io/ci/GodzHardYT/RulesUI/RulesUI